nyuhsl/data-catalog

- README.md
> flip installation steps 3 and 4

- README.md
Link to a page where a compatible version of Solr can be downloaded. 
refs #11
> include Solr version dependency

- README.md
a little whitespace goes a long way in the GitHub flavor or Markdown.
> formatting tweaks

- SolrIndexerExample.php
Since this is a PHP based project, include a PHP based indexer.
> PHP port of SolrIndexerExample.py

- app/config/security.yml.example
Add non-administrative user account for use during testing
> adding default user account for development

- src/AppBundle/EventListener/DatasetEditListener.php
Fixes a bug that was preventing dataset creation in some circumstances.
> Fix bug on dataset creation

- src/AppBundle/Entity/Security/User.php
> Fixing user creation bug

- app/Resources/views/default/admin-manage.html.twig
> Add two metadata fields to entity list

- app/Resources/views/default/view_dataset_internal.html.twig
SOLR6 did not recognize lowercase 'or' operator. Changed to uppercase.
> Update formatted author related datasets query

- src/AppBundle/Entity/SearchResults.php
- src/AppBundle/Service/SolrSearchr.php
- Use a different format for Solr's facet query results
- Calculate date ranges dynamically based on 10-year intervals
> Fixing "Timeframe" facets

- SolrIndexerExample.php
- SolrIndexerExample.py
- app/Resources/views/default/results.html.twig
Also updating URLs in Solr scripts
> Fixing how the search results are counted to improve pagination

- web/css/style.css
> Add CSS for print

- src/AppBundle/Form/Type/PublicationType.php
> Making URL field not required

- app/Resources/views/default/view_dataset.html.twig
- app/Resources/views/default/view_dataset_external.html.twig
- app/Resources/views/default/view_dataset_internal.html.twig
> Adding search links to 'Data Types' element in dataset display

- app/Resources/views/default/related_dataset_link.html.twig
- app/Resources/views/default/related_dataset_links.html.twig
- app/Resources/views/default/view_dataset.html.twig
- app/Resources/views/default/view_dataset_external.html.twig
- app/Resources/views/default/view_dataset_internal.html.twig
- src/AppBundle/Controller/RelatedDatasetController.php
> Use controller to check if related datasets should be publicly visible

- app/Resources/views/default/view_dataset_external.html.twig
- app/Resources/views/default/view_dataset_internal.html.twig
> Stop searching on the now-defunct 'corresponding_authors' field in Solr

- app/Resources/views/default/view_dataset_external.html.twig
- app/Resources/views/default/view_dataset_internal.html.twig
- app/config/dev/parameters.yml.backup
- app/config/prod/parameters.yml.backup
- src/AppBundle/Entity/Person.php
- web/css/style.css
This was an oversight in my logic, and it's fixed now. Also, I am not sure why I can never remember to put these in a separate branch.
> Author popover should show if the author has a profile but no further datasets

- src/AppBundle/Entity/Person.php
- src/AppBundle/Form/Type/PersonType.php
> Adding new metadata field to Person entity

- app/Resources/views/base.html.twig
- composer.json
- composer.lock
Symfony minor version update, jQuery major version update.
> Update Symfony to 2.8.52; jQuery to 3.4.1

- config/packages/twig.yaml
- templates/default/view_dataset_external.html.twig
- templates/default/view_dataset_internal.html.twig
> Fixing BioURL display and allowing custom local expert contact form
